### ISSUE TITLE
Dockerfile.jammy-ex1.12.2-otp24.2.1 should be replaced from ros to hexpm base image

### ISSUE THREAD

**Issue by s-hosoai** [rclex/rclex_docker#3]
Currently, Erlang / Elixir docker images for Ubuntu 22.04 (jammy) are not provided.
Replace base image when the latest elixir docker Image is available.

**Comment by takasehideki** [comment]
just a pin to hexpm/bob, which provides Docker image we use.
https://github.com/hexpm/bob/issues/112

**Comment by takasehideki** [comment]
this has been fixed in https://github.com/rclex/rclex_docker/pull/4
